# Generated by Django 3.2.22 on 2024-02-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('meat', 'Meat'), ('fish', 'Fish'), ('salad', 'Salad'), ('dessert', 'Dessert'), ('dough', 'Dough'), ('vegetables', 'Vegetables'), ('all', 'All Categories')], max_length=50, unique=True)),
            ],
        ),
    ]
