# Generated by Django 3.2.22 on 2024-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_posts', '0002_recipeposts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeposts',
            name='tags',
            field=models.CharField(blank=True, choices=[('american', 'American'), ('argentinian', 'Argentinian'), ('asian', 'Asian'), ('baked', 'Baked'), ('baking', 'Baking'), ('barbecue', 'Barbecue'), ('beef', 'Beef'), ('breakfast', 'Breakfast'), ('brazilian', 'Brazilian'), ('british', 'British'), ('casseroles', 'Casseroles'), ('chicken', 'Chicken'), ('chinese', 'Chinese'), ('comfort', 'Comfort'), ('comfort_food', 'Comfort Food'), ('curries', 'Curries'), ('dairy_free', 'Dairy Free'), ('dessert', 'Dessert'), ('dinner', 'Dinner'), ('dips', 'Dips'), ('duck', 'Duck'), ('exotic', 'Exotic'), ('fish', 'Fish'), ('french', 'French'), ('fried', 'Fried'), ('german', 'German'), ('gluten_free', 'Gluten Free'), ('gourmet', 'Gourmet'), ('greek', 'Greek'), ('grilled', 'Grilled'), ('healthy', 'Healthy'), ('holiday_special', 'Holiday Special'), ('indian', 'Indian'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('keto', 'Keto'), ('kid_friendly', 'Kid Friendly'), ('korean', 'Korean'), ('lamb', 'Lamb'), ('lebanese', 'Lebanese'), ('low_carb', 'Low Carb'), ('lunch', 'Lunch'), ('mediterranean', 'Mediterranean'), ('mexican', 'Mexican'), ('moroccan', 'Moroccan'), ('no_bake', 'No Bake'), ('nut_free', 'Nut Free'), ('one_pot', 'One Pot'), ('paleo', 'Paleo'), ('pasta', 'Pasta'), ('pizza', 'Pizza'), ('pork', 'Pork'), ('prawns', 'Prawns'), ('protein_rich', 'Protein Rich'), ('quick_easy', 'Quick and Easy'), ('quick_meals', 'Quick Meals'), ('raw', 'Raw'), ('roasted', 'Roasted'), ('russian', 'Russian'), ('salads', 'Salads'), ('salmon', 'Salmon'), ('sandwiches', 'Sandwiches'), ('seafood', 'Seafood'), ('seasonal', 'Seasonal'), ('shellfish', 'Shellfish'), ('slow_cooker', 'Slow Cooker'), ('slow_cooking', 'Slow Cooking'), ('smoked', 'Smoked'), ('snack', 'Snack'), ('soups', 'Soups'), ('spanish', 'Spanish'), ('spicy', 'Spicy'), ('stews', 'Stews'), ('stir_fried', 'Stir Fried'), ('street_food', 'Street Food'), ('sugar_free', 'Sugar Free'), ('thai', 'Thai'), ('traditional', 'Traditional'), ('tuna', 'Tuna'), ('turkey', 'Turkey'), ('turkish', 'Turkish'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('vietnamese', 'Vietnamese'), ('whole30', 'Whole30'), ('wraps', 'Wraps')], max_length=100),
        ),
    ]
