# Generated by Django 3.2.22 on 2024-02-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_category', '0001_initial'),
        ('recipe_posts', '0003_alter_recipeposts_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeposts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_posts', to='recipe_category.category'),
        ),
    ]
