# Generated by Django 3.2.22 on 2024-02-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_category', '0002_alter_category_name'),
        ('recipe_posts', '0004_recipeposts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeposts',
            name='category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipe_posts', to='recipe_category.category'),
        ),
    ]
