# Generated by Django 3.2.22 on 2024-02-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_category', '0002_alter_category_name'),
        ('recipe_posts', '0005_alter_recipeposts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeposts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_posts', to='recipe_category.category'),
        ),
    ]
