# Generated by Django 3.2.22 on 2024-02-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_rating', '0002_auto_20240205_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciperating',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together=set(),
        ),
    ]
