# Generated by Django 3.2.22 on 2024-02-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_rating', '0003_auto_20240205_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperating',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
