# Generated by Django 3.2.22 on 2024-02-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_rating', '0004_reciperating_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperating',
            name='title',
        ),
    ]
