# Generated by Django 3.2.22 on 2024-02-07 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_posts', '0004_recipeposts_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_rating', '0005_remove_reciperating_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('recipe', 'user')},
        ),
    ]
